# Generated by Django 3.2.7 on 2021-12-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(default='', max_length=300)),
                ('User_Password', models.CharField(default='', max_length=50)),
                ('User_Email', models.CharField(default='', max_length=300)),
                ('User_Phone', models.CharField(default='', max_length=20)),
                ('User_Type', models.CharField(default='', max_length=20)),
                ('User_Status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('emailid', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('mobile_Number', models.CharField(default='', max_length=30)),
                ('id_proof', models.CharField(default='', max_length=30)),
                ('id_number', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='0', max_length=10)),
                ('location', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=30)),
                ('dest', models.CharField(default='', max_length=30)),
                ('cost', models.IntegerField(default='')),
                ('date', models.DateField(default='', max_length=30)),
                ('start_time', models.CharField(default='', max_length=30)),
                ('arrival_time', models.CharField(default='', max_length=30)),
                ('no_pass', models.IntegerField(default='')),
                ('details', models.TextField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('status1', models.CharField(default='', max_length=30)),
                ('status2', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareApp.user_registration_tb')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Point', models.CharField(default='', max_length=300)),
                ('End_Point', models.CharField(default='', max_length=50)),
                ('Date', models.CharField(default='', max_length=300)),
                ('Time', models.CharField(default='', max_length=20)),
                ('Vehicle_Type', models.CharField(default='', max_length=20)),
                ('User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShareApp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=30)),
                ('dest', models.CharField(default='', max_length=30)),
                ('cost', models.IntegerField(default='')),
                ('arrival_time', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('driver_id', models.CharField(default='', max_length=30)),
                ('u_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ShareApp.user_registration_tb')),
                ('v_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ShareApp.vehiclesharing')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.CharField(default='', max_length=30)),
                ('suggestion', models.CharField(default='', max_length=30)),
                ('ext1', models.CharField(default='', max_length=30)),
                ('ext2', models.CharField(default='', max_length=30)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareApp.tbl_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShareApp.user_registration_tb')),
            ],
        ),
    ]
