# Generated by Django 3.2.7 on 2021-12-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShareApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='request',
        ),
    ]
