# Generated by Django 3.2.7 on 2022-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareApp', '0002_remove_tbl_feedback_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='link',
            field=models.CharField(default='', max_length=30),
        ),
    ]
