# Generated by Django 3.2.7 on 2022-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareApp', '0004_tbl_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
