# Generated by Django 3.2.7 on 2022-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareApp', '0005_tbl_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='ext1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='ext2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='star_rating',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='suggestion',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='arrival_time',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='date',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='dest',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='driver_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='start',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='status',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_request',
            name='time',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='tbl_route',
            name='End_Point',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tbl_route',
            name='Time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_route',
            name='Vehicle_Type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='User_Phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='User_Status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='User_Type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='emailid',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='gender',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='id_number',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='id_proof',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='location',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='mobile_Number',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='password',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user_registration_tb',
            name='user_type',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='arrival_time',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='date',
            field=models.DateField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='dest',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='details',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='gender',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='start',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='start_time',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='status1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiclesharing',
            name='status2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
