# Generated by Django 3.2.7 on 2022-01-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareApp', '0006_auto_20220125_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='cur_date',
            field=models.CharField(default='', max_length=300),
        ),
    ]
